version: '3'
services:
  api:
    image: s3ni0r/lunatech-api:1.0
    ports:
    - 9000:9000
    links:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: on-failure
  db:
    image: s3ni0r/postgres:9.5
    environment:
      - POSTGRES_USER=lunatech
      - POSTGRES_PASSWORD=lunatech
      - POSTGRES_DB=lunatech
      - PGDATA=/data
    ports:
      - 5432:5432